### ISSUE TITLE
Help Request - Cache doesn't seem to work with example settings

### ISSUE THREAD

**Issue by peavers** [meltwater/drone-cache#131]
Sorry if this is a silly question, but following the example documentation for using the local file system for cache, I'm unable to get it working. 

My config built from the example: 

```
kind: pipeline
name: default

steps:
  - name: restore-cache
    image: meltwater/drone-cache:dev
    pull: true
    settings:
      backend: "filesystem"
      restore: true
      cache_key: "volume"
      archive_format: "gzip"
      mount:
        - 'node_modules'
    volumes:
      - name: cache
        path: /tmp/cache

  - name: frontend
    image: node
    commands:
      - npm install
      - npm run build --prod

  - name: rebuild-cache
    image: meltwater/drone-cache:dev
    pull: true
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: "volume"
      archive_format: "gzip"
      mount:
        - 'node_modules'
    volumes:
      - name: cache
        path: /tmp/cache

volumes:
  - name: cache
    temp: {}
```
When a new build starts for the first time, it isn't able to find the cache as it doesn't exist yet (expected) However the second time around it's also unable to find the cache. It looks to be saving the cache after the first build though?

Do I need to do anything other than what is outlined in the documentation (do I need to mount additional volumes somewhere for example) 

Restore cache message: 
```

level=warn name=drone-cache ts=2020-07-02T10:32:54.703766971Z caller=plugin.go:115 msg="using filesystem as backend" | 1s
-- | --
2 | level=info name=drone-cache ts=2020-07-02T10:32:54.704083588Z caller=plugin.go:182 msg="using provided cache key template" | 1s
3 | level=info name=drone-cache ts=2020-07-02T10:32:54.704298003Z caller=plugin.go:166 msg="restoring directory" local=node_modules remote=droppixel-spa/volume/node_modules | 1s
4 | level=info name=drone-cache ts=2020-07-02T10:32:54.704416876Z caller=cache.go:121 component=cache msg="downloading archived directory" src=droppixel-spa/volume/node_modules | 1s
5 | level=error name=drone-cache ts=2020-07-02T10:32:54.704566803Z caller=main.go:466 err="[WARNING] restore cache, process restore failed, download get file from storage backend open /tmp/cache/droppixel-spa/volume/node_modules: no such file or directory\n"
```

Rebuild cache message:
```

level=warn name=drone-cache ts=2020-07-02T10:30:53.916914222Z caller=plugin.go:115 msg="using filesystem as backend" | 1s
-- | --
2 | level=info name=drone-cache ts=2020-07-02T10:30:53.91699779Z caller=plugin.go:182 msg="using provided cache key template" | 1s
3 | level=info name=drone-cache ts=2020-07-02T10:30:53.917038528Z caller=plugin.go:142 msg="rebuilding cache for directory" local=node_modules remote=droppixel-spa/volume/node_modules | 1s
4 | level=info name=drone-cache ts=2020-07-02T10:30:53.917075212Z caller=cache.go:57 component=cache msg="archiving directory" src=/drone/src/node_modules | 1s
5 | level=info name=drone-cache ts=2020-07-02T10:31:38.155388628Z caller=cache.go:100 component=cache msg="uploading archived directory" src=/drone/src/node_modules dst=droppixel-spa/volume/node_modules | 45s
6 | level=info name=drone-cache ts=2020-07-02T10:31:38.262099395Z caller=plugin.go:149 msg="cache built" took=44.345101064s
```
