### ISSUE TITLE
If one of the mounted folder not exists, rebuild will failed.

### ISSUE THREAD

**Issue by wagaru** [meltwater/drone-cache#134]
I will do unit test on feature branch & master branch, and e2e test only for master branch.

For unit test, I need to run `composer install`, it will generate vendor/*
For e2e test, I need to run `npm install`, it will generate node_modules/*
 
I want to cache this two folders, vendor & node_modules
However, if it is a feature branch commit, it wont run e2e test, so there will be no node_modules to cache.
And the final rebuild cache step will failed.
My local folder `/tmp/cache` will still empty after rebuild.

<img width="653" alt="螢幕快照 2020-07-21 上午11 02 14" src="https://user-images.githubusercontent.com/1768607/88007968-b5b3e580-cb41-11ea-9537-070ba9c03897.png">

Here is my example .drone.yml
```
- name: restore-cache
  pull: if-not-exists
  image: meltwater/drone-cache
  volumes:
  - name: cache
    path: /tmp/cache
  settings:
    backend: filesystem
    restore: true
    cache_key: volume
    archive_format: gzip
    mount:
    - vendor
    - node_modules

- name: unitTest
  image: php
  commands:
    - composer install
    - ./vendor/bin/phpunit
  when:
    branch:
    - feature/*
    - master

- name: e2eTest
  image: node
  commands:
    - npm install
    - npm run test
  when:
    branch:
    - master

- name: rebuild-cache
  pull: if-not-exists
  image: meltwater/drone-cache
  volumes:
  - name: cache
    path: /tmp/cache
  settings:
    backend: filesystem
    rebuild: true
    cache_key: volume
    archive_format: gzip
    mount:
    - vendor
    - node_modules
volumes:
- name: cache
  host:
    path: /tmp/cache
```
