### ISSUE TITLE
Rebuild cache condition

### ISSUE THREAD

**Issue by Fraccaman** [meltwater/drone-cache#157]
**Is your feature request related to a problem? Please describe.**
Rebuilding cache takes a lot of times, in particular if the project is big and has a lot of dependencies. 

**Describe the solution you'd like**
It would be nice to have the possibility to have a "hash mechanism": hash a list of provided files (like package.json for node), check against a previous version of it and, if changed, rebuild the cache.
This could be even easier as having the possibility to supply a boolean condition flagging if the cache needs to be rebuilt or not.

**Comment by kakkoyun** [comment]
Hey @Fraccaman, thanks for opening the issue.

We actually have this feature by using custom cache keys. You can check the documentation https://github.com/meltwater/drone-cache/blob/master/docs/cache_key_templates.md.

I'm going the close the issue. Feel free to comment for further clarification.

**Comment by Fraccaman** [comment]
Uhm, in my current build I have something like this:
```
settings:
      backend: "s3"
      rebuild: true
      bucket: s3-bucket-name
      region: eu-west-1
      cache_key: "cache"
      archive_format: "gzip"
```

As the `cache_key` field is static, does it mean that it should never rebuild the cache? Because, at the moment, it always rebuild it. 
Btw I think i can change it to something like ```{{ checksum "package.json" }}```.

**Comment by kakkoyun** [comment]
> As the cache_key field is static, does it mean that it should never rebuild the cache? Because, at the moment, it always rebuild it.

In theory, this should never rebuild. We need to have a closer look. Also, you have to have the same key for both of the steps (rebuild/restore).

> Btw I think i can change it to something like "{{ checksum "package.json" }}".

Exactly, it'd work if you change it to `"{{ checksum "package.json" }}"`.

**Comment by Fraccaman** [comment]
From my side, I can confirm that it with `cache_key: "cache"` it always rebuild, Ill try to see if I can make it work.

**Comment by Fraccaman** [comment]
I doesn't work neither with `"{{ checksum \"stack.yaml\" }}"`. Always rebuild the cache even if the the checksum is the same (there is only 1 folder in s3).

**Comment by kakkoyun** [comment]
Could you please share the version you're using and both configuration steps? And I assume stack.yaml checksum doesn't change

**Comment by Fraccaman** [comment]
Here are the steps:

```
  - name: restore-cache
    image: meltwater/drone-cache:dev
    settings:
      backend: "s3"
      restore: true
      bucket: bucket-name
      region: eu-west-1
      cache_key: "{{ checksum \"stack.yaml\" }}"
      archive_format: "gzip"
      mount:
        - ./.stack-work
        - ./.stack
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    volumes:
      - name: cache
        path: /tmp/cache

  - name: rebuild-cache
    image: meltwater/drone-cache:dev
    volumes:
      - name: cache
        path: /tmp/cache
    settings:
      backend: "s3"
      bucket: bucket-name
      region: eu-west-1
      rebuild: true
      archive_format: "gzip"
      cache_key: "{{ checksum \"stack.yaml\" }}"
      mount:
        - ./.stack-work
        - ./.stack
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
```
