### ISSUE TITLE
corrupt archive file (gzip, filesystem)

### ISSUE THREAD

**Issue by cal101** [meltwater/drone-cache#158]
**Describe the bug**

I am using the cache plugin to cache an .m2 directory.
Too often the cache gets corrupted.
Assuming that gnu tar should be able to read the archive it looks to me that the created archive is corrupt:

```
$ tar ztvf m2p2-cache/.m2 | grep xyz
tar: Removing leading `/' from member names
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

**To Reproduce**

It's not clear when and how this happens.

The configuration to store the cache is
```
  - name: rebuild-cache
    image: meltwater/drone-cache:dev
    pull: true
    settings:
      backend: "filesystem"
      rebuild: true
      #      debug: true
      cache_key: "m2p2-cache"
      archive_format: "gzip"
      mount:
        - '.m2'
        - '.p2'
    volumes:
      - name: cache
        path: /tmp/cache
    when:
      status:
        - success
        - failure
```

**Expected behavior**
Don't create corrupted files.
