### ISSUE TITLE
v1.2.0 breaks EC2 IAM role bucket access

### ISSUE THREAD

**Issue by jimsheldon** [meltwater/drone-cache#188]
**Describe the bug**

v1.2.0 introduced a regression where EC2 instances that had been using their instance role to access an S3 bucket can't anymore:

```
level=error name=drone-cache ts=2021-09-30T12:11:38.462747703Z caller=main.go:601 err=\"[IMPORTANT] restore cache, restore failed, download from &lt;masfsearch/1/maven-repo&gt; to &lt;./maven-repo&gt;, extract files from downloaded archive, pipe reader failed, tar reader &lt;get file from storage backend, pipe writer failed, get the object, AccessDenied: Access Denied\n\tstatus code: 403, request id: 28D3T3K1F818TDS2, host id: iGaoRvybXfPFR6A1ECpSJDIml2o5uU1X6o6ZYzhm08EKrsUzFXo0Y9lnYqOCOe3CKdhCPWG9Ix0=&gt;, archive not readable\n\"
```

**To Reproduce**
1. On an AWS EC2 instance where its instance role gives it read/write access to an S3 bucket, run a pipeline step like this:
```yaml
  - name: cache-restore
    pull: if-not-exists
    image: meltwater/drone-cache:v1.2.0
    settings:
      cache_key: '1'
      bucket: my-s3-bucket
      region: eu-west-1
      mount:
        - ./maven-repo
      restore: true
```

**Expected behavior**
The plugin should use the instance role of the agent to authenticate and pull files from the S3 bucket.

This seems to have started with #133
