### ISSUE TITLE
Can't cache gradle dependencies with message "no such file or directory"

### ISSUE THREAD

**Issue by KangbingZhao** [meltwater/drone-cache#235]
**Describe the bug**
can't cache gradle dependencies.

I tried to mount /root/.gradle/caches but it doesn't work.
I checked that it's exact gradle depedencies directory.

**To Reproduce**

```
kind: pipeline
type: docker
name: test
steps:
  - name: restore-cache-with-filesystem
    image: meltwater/drone-cache
    pull: if-not-exists
    settings:
      backend: "filesystem"
      restore: true
      cache_key: "volume"
      archive_format: "gzip"
      mount:
        - "/root/.gradle/caches"
    volumes:
      - name: cache
        path: /tmp/cache/gradle
  - name: pre
    image: openjdk:17-jdk-slim
    volumes:
      - name: sock
        path: /var/run/docker.sock
    commands:
      - ./gradlew build -profile -i
      - cd /root/.gradle
      - ls -a
  - name: rebuild-cache-with-filesystem
    image: meltwater/drone-cache
    pull: if-not-exists
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: "volume"
      archive_format: "gzip"
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - "/root/.gradle/caches"
    volumes:
      - name: cache
        path: /tmp/cache/gradle
volumes:
  - name: sock
    host:
      path: /var/run/docker.sock
  - name: cache
    host:
      path: /tmp/cache/gradle
```

## Specifications

  - Version:  drone 2.15.0
  - Platform: Linux
  - Subsystem: Ubuntu 20.04 in WSL2
