### ISSUE TITLE
Enable Assume Role from Drone Pipeline Step

### ISSUE THREAD

**Issue by hec-hi** [meltwater/drone-cache#248]
In my DroneCI Pipeline, I am able to use drone-cache when providing IAM User credentials directly as environment variables. 
Example:
```yaml
steps:
  - name: restore-cache
    image: meltwater/drone-cache
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: <DRONE_SECRET_AWS_ACCESS_KEY_ID>
      AWS_SECRET_ACCESS_KEY:
        from_secret: <DRONE_SECRET_AWS_SECRET_ACCESS_KEY>
    settings:
      <SETTINGS>
```
Due to compliance reasons, I would like to assume a role instead:
```yaml
steps:
  - name: restore-cache
    image: meltwater/drone-cache
    environment:
      AWS_ASSUME_ROLE_ARN:
        from_secret: <DRONE_SECRET_ROLE_ARN>
    settings:
      <SETTINGS>
```
I see something in that direction was already implemented in https://github.com/meltwater/drone-cache/issues/142 , but setting the environment variable `AWS_ASSUME_ROLE_ARN` did not seem to work out-of-the-box for me. 
Maybe this is already implemented, and I am just missing something 😄 

Thanks in advance!

**Comment by hec-hi** [comment]
Also, an interesting behavior I observed: any time I provide `AWS_ASSUME_ROLE_ARN` I end up having the `EmptyStaticCreds: static credentials are empty` error. Even if my step looks like
```yaml
steps:
  - name: restore-cache
    image: meltwater/drone-cache
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: <DRONE_SECRET_AWS_ACCESS_KEY_ID>
      AWS_SECRET_ACCESS_KEY:
        from_secret: <DRONE_SECRET_AWS_SECRET_ACCESS_KEY>
      AWS_ASSUME_ROLE_ARN:
        from_secret: <DRONE_SECRET_ROLE_ARN>
    settings:
      <SETTINGS>
```
If I remove `AWS_ASSUME_ROLE_ARN` the plugin works again.
