### ISSUE TITLE
Can't cache `bundle install`

### ISSUE THREAD

**Issue by aamarill** [meltwater/drone-cache#52]
## Expected Behavior
Successfully cache the `/usr/local/lib/ruby` directory

## Actual Behavior
```
[rebuild-cache-with-filesystem:1] 2019/08/20 22:40:17 [WARNING] could not build cache, process rebuild failed, could not mount </usr/local/lib/ruby>, make sure file or directory exists and readable: stat /usr/local/lib/ruby: no such file or directory
```

## Steps to Reproduce the Problem

  1. Add The following .drone.yml and Gemfile

```yaml
# .drone.yml
---
kind: pipeline
name: default

steps:
- name: restore-cache-with-filesystem
  image: meltwater/drone-cache:dev
  pull: true
  settings:
    backend: "filesystem"
    restore: true
    cache_key: "${DRONE_REPO_NAME}"
    archive_format: "gzip"
    mount:
    - '/usr/local/lib/ruby'
  volumes:
  - name: cache
    path: /tmp/cache

- name: step1
  image: ruby:2.3.1
  commands:
  - bundle install
  - cd /usr/local/lib/ruby
  - ls -al

- name: rebuild-cache-with-filesystem
  image: meltwater/drone-cache:dev
  pull: true
  settings:
    backend: "filesystem"
    rebuild: true
    cache_key: "${DRONE_REPO_NAME}"
    archive_format: "gzip"
    mount:
    - '/usr/local/lib/ruby'
  volumes:
  - name: cache
    path: /tmp/cache

volumes:
  - name: cache
    host:
      path: /tmp/cache/

```
---
```ruby
# Gemfile
source 'https://rubygems.org'
ruby "2.3.1"
gem 'byebug'
gem 'colorize'
gem 'faker'
gem 'json_pure'
gem 'mysql2', '~> 0.5'
gem 'rake'
gem 'rest-client', '~> 2.0.2'
gem 'rspec', '~> 3.5.0'
gem 'rubocop'
gem 'aws-sdk-sqs', '~> 1.16.0'
gem 'sinatra', '~> 2.0.5'
```

  2. Run `$ drone exec --trusted`

## Specifications
OS - Mac OS Mojave
```
$ drone -v
drone version 1.1.1
```

Thank you for the awesome plugin and help in advance 😄
